#!/usr/bin/env tsx
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { TrackEvent } from '../src/core/tracker.js';

interface Group { key: string; count: number; events: TrackEvent[]; chars: Record<string, number>; }

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
const log = arg('--log') ?? arg('-l') ?? 'events.jsonl';
const out = arg('--out') ?? 'tests/fixtures/real-shapes.generated.ts';
const write = process.argv.includes('--write');
const limit = Number(arg('--limit') ?? 5000);

if (!fs.existsSync(log)) {
  console.error(`events log not found: ${log}`);
  process.exit(1);
}
const lines = fs.readFileSync(log, 'utf8').trim().split(/\r?\n/).filter(Boolean).slice(-limit);
const groups = new Map<string, Group>();
let minTs = Number.POSITIVE_INFINITY, maxTs = 0, parsed = 0;
for (const line of lines) {
  let ev: TrackEvent;
  try { ev = JSON.parse(line) as TrackEvent; } catch { continue; }
  parsed++;
  const ts = Date.parse(ev.ts); if (Number.isFinite(ts)) { minTs = Math.min(minTs, ts); maxTs = Math.max(maxTs, ts); }
  const buckets = ev.bucket_chars ?? {};
  const mix = Object.entries(buckets).filter(([, v]) => (v ?? 0) > 0).sort((a,b)=>(b[1]??0)-(a[1]??0)).slice(0,3).map(([k])=>k).join('+') || 'none';
  const key = [ev.model ?? 'unknown-model', ev.path ?? 'unknown-path', ev.system_sha8 ?? 'no-system', mix].join('|');
  const g = groups.get(key) ?? { key, count: 0, events: [], chars: {} };
  g.count++;
  if (g.events.length < 3) g.events.push(ev);
  for (const [b, n] of Object.entries(buckets)) g.chars[b] = (g.chars[b] ?? 0) + (typeof n === 'number' ? n : 0);
  groups.set(key, g);
}
const top = [...groups.values()].sort((a,b)=>b.count-a.count).slice(0,20);
const generated = `// Generated by scripts/extract-real-shapes.ts.\n// Source: ${path.resolve(log)}\n// Date range: ${Number.isFinite(minTs) ? new Date(minTs).toISOString() : 'n/a'} — ${maxTs ? new Date(maxTs).toISOString() : 'n/a'}\n// Events parsed: ${parsed}\n\nexport const REAL_SHAPE_DRIFT_REPORT = ${JSON.stringify(top.map(g => ({ key: g.key, count: g.count, bucketChars: g.chars, representatives: g.events.map(e => ({ ts: e.ts, compressed: e.compressed, reason: e.reason, model: e.model, path: e.path, system_sha8: e.system_sha8, bucket_chars: e.bucket_chars })) })), null, 2)} as const;\n`;
console.log(`source=${path.resolve(log)}`);
console.log(`date_range=${Number.isFinite(minTs) ? new Date(minTs).toISOString() : 'n/a'}..${maxTs ? new Date(maxTs).toISOString() : 'n/a'}`);
console.log(`events=${parsed} groups=${groups.size} output=${out}`);
if (write) {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, generated);
  console.log(`wrote ${out}`);
} else {
  console.log('dry-run only; pass --write to update the fixture file');
  console.log(generated.slice(0, 4000));
}
